In [1]:
import pandas as pd
import numpy as np
import pickle
import csv

In [2]:
x = pd.read_csv('train_X_re.csv')
y = pd.read_csv('train_Y_re.csv',header=None)

In [3]:
x

avg_time_week  project_rate  practice_sets_score  activity  streak  \
0              6.0           6.0                324.0       8.0     0.0   
1              6.0          10.0                326.0       7.0     1.0   
2              4.0           7.0                338.0       9.0     1.0   
3              8.0           5.0                334.0       8.0     1.0   
4              4.0           8.0                299.0       4.0     1.0   
..             ...           ...                  ...       ...     ...   
370            8.0           9.0                333.0       8.0     1.0   
371            8.0           7.0                325.0       9.0     0.0   
372            2.0           6.0                317.0       5.0     1.0   
373           10.0           8.0                339.0       8.0     1.0   
374           10.0           9.0                346.0      10.0     1.0   

     quiz_score  regularity  
0         114.0        8.82  
1         112.0        8.99  
2         122.0        9.38  
3         114.0        9.04  
4         101.0        7.82  
..          ...         ...  
370       115.0        9.02  
371       107.0        8.68  
372       103.0        8.45  
373       117.0        9.30  
374       119.0        9.08  

[375 rows x 7 columns]

In [4]:
y

0
0    46.10
1    62.10
2    66.67
3    59.81
4    46.86
..     ...
370  62.10
371  56.00
372  52.19
373  65.90
374  70.48

[375 rows x 1 columns]

In [5]:
x.isnull().sum()

avg_time_week          0
project_rate           0
practice_sets_score    0
activity               0
streak                 0
quiz_score             0
regularity             0
dtype: int64

In [6]:
y.isnull().sum()

0    0
dtype: int64

In [7]:
x.head()

avg_time_week  project_rate  practice_sets_score  activity  streak  \
0            6.0           6.0                324.0       8.0     0.0   
1            6.0          10.0                326.0       7.0     1.0   
2            4.0           7.0                338.0       9.0     1.0   
3            8.0           5.0                334.0       8.0     1.0   
4            4.0           8.0                299.0       4.0     1.0   

   quiz_score  regularity  
0       114.0        8.82  
1       112.0        8.99  
2       122.0        9.38  
3       114.0        9.04  
4       101.0        7.82

In [8]:
x = x.values
x

array([[  6.  ,   6.  , 324.  , ...,   0.  , 114.  ,   8.82],
       [  6.  ,  10.  , 326.  , ...,   1.  , 112.  ,   8.99],
       [  4.  ,   7.  , 338.  , ...,   1.  , 122.  ,   9.38],
       ...,
       [  2.  ,   6.  , 317.  , ...,   1.  , 103.  ,   8.45],
       [ 10.  ,   8.  , 339.  , ...,   1.  , 117.  ,   9.3 ],
       [ 10.  ,   9.  , 346.  , ...,   1.  , 119.  ,   9.08]])

In [9]:
y = y.values

In [10]:
y

array([[46.1 ],
       [62.1 ],
       [66.67],
       [59.81],
       [46.86],
       [35.43],
       [69.71],
       [51.43],
       [62.1 ],
       [45.33],
       [71.24],
       [46.1 ],
       [65.9 ],
       [52.19],
       [39.24],
       [57.52],
       [69.71],
       [37.71],
       [38.48],
       [46.1 ],
       [44.57],
       [55.24],
       [52.19],
       [62.1 ],
       [69.71],
       [38.48],
       [69.71],
       [55.24],
       [45.33],
       [50.67],
       [52.95],
       [67.43],
       [52.19],
       [30.1 ],
       [52.19],
       [47.62],
       [46.86],
       [52.19],
       [46.1 ],
       [55.24],
       [48.38],
       [62.86],
       [68.95],
       [64.38],
       [44.57],
       [56.76],
       [44.57],
       [55.24],
       [68.19],
       [48.38],
       [46.86],
       [40.76],
       [37.71],
       [54.48],
       [33.9 ],
       [49.14],
       [67.43],
       [58.29],
       [33.14],
       [52.95],
       [61.33],
       [30.86],
       [

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.25,random_state = 0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [13]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighb)

In [14]:
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [15]:
predictions = regressor.predict(x_test)


In [16]:
predictions,y_test

(array([42.29, 39.24, 59.05, 49.9 , 47.62, 30.86, 67.43, 62.86, 42.29,
        54.48, 58.29, 56.  , 56.  , 43.05, 51.43, 41.52, 35.43, 56.  ,
        49.9 , 27.05, 63.62, 56.  , 39.24, 39.24, 45.33, 46.86, 64.38,
        59.81, 69.71, 54.48, 39.24, 65.9 , 52.19, 45.33, 63.62, 69.71,
        45.33, 69.71, 70.48, 68.95, 42.29, 30.1 , 55.24, 63.62, 59.05,
        62.86, 60.57, 41.52, 44.57, 49.9 , 39.24, 54.48, 44.57, 41.52,
        56.  , 59.05, 56.  , 53.71, 52.95, 65.9 , 59.81, 52.19, 70.48,
        41.52, 70.48, 62.1 , 52.19, 65.9 , 42.29, 53.71, 47.62, 65.9 ,
        62.86, 54.48, 59.05, 65.14, 57.52, 45.33, 65.14, 47.62, 35.43,
        54.48, 52.19, 41.52, 45.33, 42.29, 52.19, 48.38, 43.05, 52.19,
        52.19, 67.43, 39.24, 48.38]),
 array([[44.57],
        [56.  ],
        [61.33],
        [49.9 ],
        [49.9 ],
        [35.43],
        [67.43],
        [63.62],
        [32.38],
        [37.71],
        [57.52],
        [56.76],
        [61.33],
        [36.95],
        [52.19

In [17]:
predictions = predictions.reshape(len(y_test),1)

In [18]:
predictions

array([[42.29],
       [39.24],
       [59.05],
       [49.9 ],
       [47.62],
       [30.86],
       [67.43],
       [62.86],
       [42.29],
       [54.48],
       [58.29],
       [56.  ],
       [56.  ],
       [43.05],
       [51.43],
       [41.52],
       [35.43],
       [56.  ],
       [49.9 ],
       [27.05],
       [63.62],
       [56.  ],
       [39.24],
       [39.24],
       [45.33],
       [46.86],
       [64.38],
       [59.81],
       [69.71],
       [54.48],
       [39.24],
       [65.9 ],
       [52.19],
       [45.33],
       [63.62],
       [69.71],
       [45.33],
       [69.71],
       [70.48],
       [68.95],
       [42.29],
       [30.1 ],
       [55.24],
       [63.62],
       [59.05],
       [62.86],
       [60.57],
       [41.52],
       [44.57],
       [49.9 ],
       [39.24],
       [54.48],
       [44.57],
       [41.52],
       [56.  ],
       [59.05],
       [56.  ],
       [53.71],
       [52.95],
       [65.9 ],
       [59.81],
       [52.19],
       [

In [19]:
mse = np.sum(np.square(y_test - predictions))

In [20]:
mse

3988.3401

In [21]:
pickle.dump(regressor,open('MODEL_FILE.sav','wb'))

ValueError: Number of features of the model must match the input. Model n_features is 7 and input n_features is 1 